/*
 *	File		:	CLK.1.0.1.c
 *	Date		:	2017/1/12
 *	Author		:	Nguyen Chinh Thuy
 *	Version		:	1.0.1
 *	Description	:	Source of Clock
 */
/**************************************************************************************************
 *	INCLUDEs
 *************************************************************************************************/
/* Standard */

/* Producer */

/* My */

/* This project */
#include "CLK.1.0.1.h"


/**************************************************************************************************
 *	PRIVATEs
 *************************************************************************************************/
/*  */
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
//-------------------------------------------------------------------------------------------------


/**************************************************************************************************
 *	PUBLICs
 *************************************************************************************************/
/* Frequency of Clock */
uint32_t		ui32ClkFreq = 16000000;		// As default (f_PIOSC = 16MHz)
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:	CLK_SRC_: Clock source
 *					CLK_PLL_:	Use PLL or not
 *					freq: Required clock frequency
 *	Output		:	None
 *	Description	:	Setup system clock
 */
void
clkSetup(uint32_t CLK_SRC_, uint32_t CLK_PLL_, uint32_t CLK_FREQ_)
{
	ui32ClkFreq = SysCtlClockFreqSet(CLK_SRC_ 			|		// Clock source
									CLK_PLL_ 			|		// Use of PLL or not
									SYSCTL_XTAL_25MHZ 	|		// External crystal
									SYSCTL_CFG_VCO_480,			// f_VCO of PLL
									CLK_FREQ_);					// Required clock frequency
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelayCycle(uint32_t ui32Cycle)
{
	SysCtlDelay(ui32Cycle / 3);
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelayUs(uint32_t ui32Us)
{
	uint32_t	ui32Cycle = ui32ClkFreq / 1000000 * ui32Us;
	SysCtlDelay(ui32Cycle/3);
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelayMs(uint32_t ui32Ms)
{
	uint32_t	ui32Cycle = ui32ClkFreq / 1000 * ui32Ms;
	SysCtlDelay(ui32Cycle/3);
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:	None
 *	Output		:	None
 *	Description	:	Delay exactly 1us using NOP command, just used for ui32ClkFreq = 120MHz
 */
void	clkDelay1Us(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:	None
 *	Output		:	None
 *	Description	:	Delay exactly 10us using NOP command, just used for ui32ClkFreq = 120MHz
 */
void	clkDelay10Us(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}

//-------------------------------------------------------------------------------------------------
/*
 *	Input		:	None
 *	Output		:	None
 *	Description	:	Delay exactly 10us using NOP command, just used for ui32ClkFreq = 120MHz
 */
void	clkDelay100Us(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelay10Cycle(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelay100Cycle(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
void	clkDelay1000Cycle(void)
{
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;	NOP;
}
//-------------------------------------------------------------------------------------------------
/*
 *	Input		:
 *	Output		:
 *	Description	:
 */
//-------------------------------------------------------------------------------------------------


